language: node_js
node_js:
  - 'stable'
install: npm install
env:
  - DATABASE_TEST=mongodb+srv://edgar:edgar@cluster0.jpzrn.mongodb.net/personalPortfolioTestWithMocha?retryWrites=true&w=majority
node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: false
script:
  - npm test
after_success:
  - npm run coveralls